const EatingVerbs = [
    "nom",
    "chew",
    "chomp",
    "chaw",
    "chow down",
    "eet",
    "nyam",
    "eat",
    "scoff",
    "inhale",
    "nom nom nom",
    "nibble",
    "demolish",
    "swallow",
    "consume",
    "devour",
    "ingest",
    "partake of",
    "gobble",
    "gulp",
    "bolt",
    "wolf",
    "cram down",
    "finish",
    "munch",
    "guzzle",
    "put away",
    "tuck into",
    "dispose of",
    "make short work of",
    "polish off",
    "shovel down",
    "get stuck into",
    "snack",
    "destroy",
    "annihilate",
    "ingurgitate",
    "destroy",
    "obliterate",
];

module.exports = {
    EatingVerbs
}