const HatProperties = [
    "it can never remove",
    "is cursed",
    "once belonged to a God",
    "belonged to its grandmother",
    "belonged to an ancient spirit",
    "disappears when embarrassed",
    "can't count to ten",
    "is highly fashionable",
    "was once highly fashionable",
    "is itself sentient",
    "casts powerful spells",
    "enjoys long walks on the beach",
    "minds its own business",
    "takes on me",
    "will never give you up and never let you down",
    "absorbs solar radiation",
    "has a power level of over 9000",
    "is highly radioactive",
    "rules a small country",
    "has walked five thousand miles and will walk five thousand more",
    "has walked five thousand miles and won't walk a step more",
    "has a gravitational mass of a million suns",
    "has the power of a thousand exploding suns",
    "is better than your hat",
    "always disappoints",
    "yeets itself on occasion",
    "listens to the wrong music",
    "is a bad influence",
    "is always learning",
    "looks incredibly spiffy",
    "has its own terrible secret",
    "is made of skin",
    "is made of feathers",
    "is made of exotic materials",
    "enables space travel",
    "enables flight",
    "enables the wearer to grow or shrink at will",
    "must be cast into the firey chasm from whence it came",
    "is the One Hat To Rule Them All",
    "entitles the wearer to the Rule of the Ancient Kingdom of Grib",
    "causes excitement in viewers",
    "causes boils to break out on the skin",
    "causes epidemics",
    "causes pandemics",
    "sparks joy",
    "is very interesting and everyone likes it",
    "is a conversation piece at parties",
    "sparks dislike",
    "is evil",
    "is the essence of goodness",
    "is the essence of wetness",
    "is a disappointment to its parents",
    "is a better judge than most of the Supreme Court",
    "sucks",
    "rules",
    "blows",
    "is rad",
    "is radical",
    "is more than the sum of its parts",
    "is always hungry",
    "is always curious",
    "increases INT by +4",
    "increases DEX by +2",
    "increases WIS by +1",
    "is more fun than your mum",
    "has its own source of heat",
    "taps into a forbidden power from another universe",
    "itself contains a self-contained pocket universe, in which eons take place in the space of a single second",
    "contains multitudes",
    "writes erotic fan-fiction",
    "protects the wearer from all disease",
    "sparks fire",
    "sparks ennui",
    "sparks inspiration",
    "is lost",
    "helps the wearer find lost objects",
    "attracts bees",
    "attracts beneficial insects",
    "cannot spel",
    "fixes dyslexia for all people within a square mile",
    "enables the wearer to leap tall buildings in a single bound",
    "is both redundant and recursive and redundant and recursive and redundant and recursive",
    "talks about Fight Club",
    "causes excessive yawning",
    "causes excessive talking",
    "causes excessive biting",
    "causes excessive yeeting",
    "is slippery",
    "is fuzzy",
    "enhances curves",
    "enhances beaks",
    "enhances tails",
    "enhances enhancements",
    "enhances eyes",
    "enchants the beholder",
    "enchants onlookers",
    "enchants other birds",
    "gives the wearer the ability to have abilities",
    "grants a boon",
    "grants a wish",
    "grants the bearer a devoted servant called Grant",
    "can pollinate nearby flowers",
    "runs on fossil fuels",
    "runs on electricity",
    "also has secrets",
    "contains other, smaller hats",
    "won't",
    "can't",
    "hasn't",
    "shan't",
    "knows what purple is",
    "knows why purple is",
    "did not participate in Gamergate",
    "is too old for this",
    "can sing",
    "moves about on thousands of tiny legs",
    "roams the house at night in search of flesh",
    "simply cannot",
    "screams \"Good Day Sir.\"",
    "fades out, again",
    "is grateful for our Iron Lung",
    "grants additional brainpower",
    "knows The Secret",
    "hates this one weird trick",
    "screams and screams and screams and screams",
    "emits a constant low-frequency humming",
    "reminds you of the lyrics to a song you forgot",
    "aids in the writing of erotic fan-fiction",
    "knows what's what",
    "knows who's who",
    "is very tiny and cute",
    "is cool",
    "is mint",
    "is a different colour from the colour it appears to be",
    "is a credit to its maker"
];

module.exports = {
    HatProperties
}