const NZPlaces = [
    "North Cape",
    "Houhora",
    "Motutangi-Kareponia",
    "Karikari Peninsula-Maungataniwha",
    "Taipa Bay-Mangonui",
    "Inlet-Rangaunu Harbour",
    "Awanui",
    "Herekino",
    "Kaitaia West",
    "Ahipara",
    "Kaitaia East",
    "Waipahihi",
    "Kermadec Islands",
    "Oceanic-Northland Region",
    "Mangapa-Matauri Bay",
    "Kaeo",
    "Inlet-Whangaroa Harbour",
    "Hokianga North",
    "Hokianga South",
    "Rawene",
    "Oceanic-Kermadec Islands",
    "Inlet-Hokianga Harbour",
    "Omapere and Opononi",
    "Inlet-Doubtless Bay",
    "Opoho",
    "Okaihau",
    "Kohukohu",
    "Waihou Valley-Hupara",
    "Ngapuhi-Kaikou",
    "Ohaeawai",
    "Moerewa",
    "Waitangi",
    "Kaikohe",
    "Kapiro",
    "Bay of Islands",
    "Kerikeri",
    "Pokere-Waihaha",
    "Haruru Falls",
    "Opua East",
    "Paihia",
    "Russell",
    "Kawakawa",
    "Punaruku-Kiripaka",
    "Tikipunga East",
    "Ngunguru",
    "Springs Flat",
    "Hikurangi",
    "Opouteke-Tanekaha",
    "Inlet-Bay of Islands",
    "Tikipunga West",
    "Wakari",
    "Three Mile Bush",
    "Te Hihi",
    "Maungatapere",
    "Wharekohe-Oakleigh",
    "Abbey Caves",
    "Pataua-Whareora",
    "Parua Bay",
    "Parahaki",
    "Bream Head",
    "Port-Limeburners",
    "Waiotira-Springfield",
    "Otaika-Portland",
    "Inlet-Whangarei Harbour",
    "Marsden Point-Ruakaka",
    "Bream Bay",
    "Waipu",
    "Kamo West",
    "Inlet-Tutukaka Harbour",
    "Kamo East",
    "Maunu",
    "Whau Valley",
    "Mairtown",
    "Otangarei",
    "Kensington",
    "Vinetown",
    "Western Hills",
    "Regent",
    "Whangarei Central",
    "Riverside",
    "Woodhill",
    "Morningside",
    "Horahora",
    "Raumanga West",
    "Raumanga East",
    "Sherwood Rise",
    "Onerahi",
    "Dargaville",
    "Kaipara Coastal",
    "Maungaru",
    "Huntly East",
    "Te Kopuru",
    "Rehia-Oneriri",
    "Ruawai",
    "Maungaturoto",
    "Mangawhai Heads",
    "Mangawhai",
    "Kaiwaka",
    "Cape Rodney",
    "Cape Rodney South",
    "Matheson Bay",
    "Matakana",
    "Point Wells",
    "Omaha",
    "Warkworth",
    "Snells Beach",
    "Algies Bay",
    "Mahurangi",
    "Kawau",
    "Wellsford",
    "Tauhoa-Puhoi",
    "Inlet-Mangawhai Harbour",
    "Orewa",
    "Oceanic-Auckland Region East",
    "Inlet-Kaipara Harbour North",
    "Inlet-Kaipara Harbour South",
    "Campbells Bay",
    "Sunnynook",
    "Mairangi Bay",
    "Windsor Park",
    "Murrays Bay",
    "Rothesay Bay",
    "Oaktree",
    "Browns Bay",
    "Waiake",
    "Glamorgan",
    "Awaruku",
    "Torbay",
    "Waiwera",
    "Hatfields Beach",
    "Red Beach West",
    "Inlet-Port Whangarei",
    "Red Beach East",
    "Stanmore Bay West",
    "Stanmore Bay East",
    "Wade Heads",
    "Crum Park",
    "Manly",
    "Army Bay",
    "Leigh",
    "Gulf Harbour Marina",
    "Gulf Harbour",
    "Weiti River",
    "Silverdale South",
    "Dairy Flat-Redvale",
    "Silverdale North",
    "Silverdale Central",
    "Tahekeroa",
    "Kinloch",
    "Albany",
    "Fairview",
    "Northcross",
    "Paremoremo East",
    "North Harbour West",
    "North Harbour East",
    "Pinehill",
    "Unsworth Heights",
    "Greenhithe",
    "Inlet-Waitemata Harbour",
    "Target Road",
    "Glendhu",
    "Witheford",
    "Kaipatiki",
    "Windy Ridge",
    "Huntly West",
    "Glenfield North",
    "Lynnmall",
    "Rototuna",
    "Forrest Hill",
    "Flagstaff",
    "Glenfield Central",
    "Sunnybrae",
    "Stillwater",
    "Monarch Park",
    "Long Bay",
    "Kaukapakapa",
    "Helensville",
    "Parakai Rural",
    "Parakai Urban",
    "Kaukapakapa Rural",
    "Helensville South",
    "Riverhead Urban",
    "Kumeu East",
    "Huapai",
    "Kumeu West",
    "Waimauku",
    "Paremoremo West",
    "Riverhead",
    "Vipond",
    "Rewiti",
    "Waitakere West",
    "Whenuapai West",
    "Taupaki",
    "Acacia Bay",
    "Hobsonville East",
    "Hobsonville South",
    "Huntington",
    "Lucken Point",
    "West Harbour",
    "Westgate",
    "Golfland",
    "Royal Heights",
    "Royal Road West",
    "Massey West",
    "Birdwood West",
    "Waimumu North",
    "Orewa West",
    "Waimumu South",
    "Kingdale",
    "Fairdene",
    "Urlich",
    "Ranui Domain",
    "Starling Park",
    "Sturges North",
    "Ranui South",
    "Swanson",
    "Waitakere",
    "Swanson South",
    "Henderson North",
    "Kelston Central",
    "Henderson South",
    "Durham Green",
    "Matipo",
    "Te Atatu Central",
    "Wakeling",
    "Edmonton",
    "Chedworth",
    "Mcleod",
    "Rewarewa",
    "Burswood",
    "Enderley",
    "Fruitvale",
    "South Head",
    "New Lynn North",
    "New Lynn South",
    "Waipareira West",
    "Glendene South",
    "Glendene North",
    "Muriwai Beach",
    "Sunnyvale",
    "Herald",
    "Parrs Park West",
    "Parrs Park",
    "Oratia",
    "Otimai",
    "Oratia West",
    "Glen Eden East",
    "Opanuku",
    "Henderson West",
    "Palm Heights",
    "Utuhina",
    "Birdwood East",
    "McLaren Park",
    "Karekare",
    "Tangutu",
    "Woodglen",
    "Green Bay",
    "Kaurilands",
    "Titirangi South",
    "Clarkin",
    "Konini",
    "Waima",
    "Laingholm",
    "Westlake",
    "Wairoa",
    "Lake Pupuke",
    "Crown Hill",
    "Castor Bay",
    "Naylor",
    "Bayswater",
    "Seacliffe",
    "Hauraki",
    "Takapuna Central",
    "Mt Victoria",
    "Stanley Bay",
    "Narrow Neck",
    "Birkdale North",
    "Beachhaven North",
    "New Windsor",
    "Beachhaven South",
    "Birkdale South",
    "Kauri Park",
    "Chelsea",
    "Birkenhead East",
    "Tidal-Waitemata Harbour",
    "Glenavon",
    "Northcote South",
    "Ocean View",
    "Tuff Crater",
    "Blockhouse Bay",
    "Avondale South",
    "Roberton",
    "Armour Bay",
    "Waterview",
    "Avondale West",
    "Rosebank",
    "Point Chevalier South",
    "Point Chevalier West",
    "Point Chevalier East",
    "Westmere",
    "Lynmore",
    "Grey Lynn West",
    "Surrey Crescent",
    "Grey Lynn East",
    "Inlet-Takapuna Head",
    "St Lukes North",
    "Herne Bay",
    "Newton",
    "Freemans Bay",
    "Arch Hill",
    "Newmarket",
    "Eden Terrace",
    "St Marys",
    "Ponsonby West",
    "Ponsonby East",
    "Epsom North",
    "Auckland Central West",
    "Auckland Harbourside",
    "Hamilton East",
    "Auckland Central East",
    "Queenwood",
    "Balmacewen",
    "Auckland City-Marinas",
    "Grafton West",
    "Great Barrier Island",
    "Kaikoura and Rangiahua Islands",
    "Cape Barrier",
    "Inlet-Hobson Bay",
    "Epsom Central",
    "Epsom South",
    "Parnell West",
    "Parnell East",
    "Meadowbank North",
    "Meadowbank South",
    "St Johns",
    "Mt Wellington Domain",
    "Glen Innes North",
    "Remuera West",
    "Glen Innes West",
    "Hamilton Central",
    "Glen Innes East",
    "Point England",
    "Waitaramoa",
    "Orakei South",
    "Waiata",
    "Mt Hobson",
    "Remuera South",
    "Abbotts Park",
    "Ellerslie North",
    "Orakei North",
    "Mission Bay",
    "Kohimarama West",
    "Kohimarama East",
    "St Heliers",
    "Glendowie",
    "Waiheke Island",
    "Tidal-Waiheke Island",
    "Caversham",
    "Islands-Motutapu Rangitoto Rakino",
    "Owairaka East",
    "Owairaka West",
    "Springleigh",
    "Mt Albert Central",
    "Kingsland",
    "Rakitu Island",
    "Browns Island",
    "Aiguilles Island",
    "St Lukes",
    "Sandringham North",
    "Sandringham East",
    "Sandringham West",
    "Grafton East",
    "Mt Eden North",
    "Sherbourne",
    "Balmoral",
    "Frankton Junction",
    "Mt Eden East",
    "Maungawhau",
    "Mt Eden South",
    "Three Kings",
    "Royal Oak",
    "Melville",
    "Hillsborough East",
    "Hillsborough West",
    "Cambridge North",
    "Walmsley",
    "Riverlea",
    "Leamington East",
    "Wesley",
    "Leamington West",
    "Akarana",
    "Lynfield North",
    "Lynfield South",
    "Waikowhai West",
    "Waikowhai East",
    "Onehunga North East",
    "Onehunga North West",
    "Onehunga South West",
    "Onehunga South East",
    "Oranga",
    "Te Papapa",
    "Oceanic-Auckland Region West",
    "Inlet-Manukau Harbour",
    "Tidal-Manukau Harbour North",
    "Tidal-Manukau Harbour",
    "University",
    "Ellerslie South",
    "Mt St John",
    "Bays-Waiheke Island",
    "One Tree Hill East",
    "Pukete West",
    "Penrose",
    "Howick West",
    "One Tree Hill Central",
    "Mt Wellington West",
    "Mt Wellington North",
    "Panmure Basin",
    "Tamaki",
    "Tidal-Eastern Bays",
    "Tidal-Tamaki",
    "Tamaki Strait",
    "Tidal-Motutapu and Browns Islands",
    "Mt Wellington South",
    "Glenview",
    "Little Barrier Island",
    "Inlet-Port Fitzroy",
    "Raglan",
    "Hamlin",
    "Ferndale",
    "Kenmure",
    "Howick Central",
    "Howick South",
    "Highland Park",
    "Mellons Bay",
    "Cockle Bay",
    "Kohuora",
    "Mangere East",
    "Papatoetoe West",
    "Papatoetoe North",
    "Papatoetoe Central",
    "Dingwall",
    "Peacocke",
    "Mornington",
    "Papatoetoe East",
    "Peachgrove",
    "Puhinui North",
    "Puhinui South",
    "Ohaupo",
    "Bucklands and Eastern Beaches",
    "Bucklands Beach South",
    "Claudelands",
    "Bleakhouse",
    "Half Moon Bay",
    "Pigeon Mountain North",
    "Murvale",
    "Pigeon Mountain South",
    "Elsmore Park",
    "Edgewater",
    "Pakuranga Central",
    "Pakuranga East",
    "Pakuranga North",
    "Sunnyhills",
    "Grange",
    "Otara West",
    "Wymondley",
    "Otara North",
    "Otara East",
    "Ferguson",
    "Otara South",
    "Meadowland",
    "Millhouse",
    "Kilkenny",
    "Highbrook",
    "Greenmount",
    "Dannemora",
    "Baverstock Oaks",
    "Point View",
    "Mission Heights",
    "Redoubt East",
    "Stonefields",
    "Rongomai",
    "Donegal Park",
    "Clover Park",
    "Half Moon Bay Marina",
    "Redoubt North",
    "Turanga",
    "Bryant",
    "Forbury",
    "Shelly Park",
    "Beachlands-Maraetai",
    "Ambury",
    "Mangere Bridge",
    "Mangere South",
    "Favona North",
    "Favona West",
    "Favona South",
    "Harania East",
    "Harania West",
    "Harania North",
    "Arahanga",
    "Viscount",
    "Mangere Central",
    "Mascot",
    "Aorere",
    "Manurewa Central",
    "Beerescourt",
    "Mangere Station",
    "Ahuriri",
    "Beaumont",
    "Hillpark",
    "Manurewa East",
    "Totara Heights",
    "Hyperion",
    "Randwick Park",
    "Ardmore",
    "Redoubt South",
    "Fairview Downs",
    "Clevedon",
    "Drury",
    "Kawakawa-Orere",
    "Takanini South",
    "Takanini North",
    "Takanini West",
    "Wattle Farm",
    "Leabank",
    "Weymouth East",
    "Weymouth West",
    "Clendon North",
    "Clendon South",
    "Burbank",
    "Rowandale",
    "Homai East",
    "Manukau Central",
    "Wiri",
    "Inlet-Firth of Thames",
    "Otahuhu West",
    "Insoll",
    "Middlemore",
    "Vauxhall",
    "Otahuhu North",
    "Fairburn",
    "Otahuhu East",
    "Papakura North",
    "Porritt",
    "Papakura Central",
    "Papakura North East",
    "Papakura East",
    "Massey Park",
    "Red Hill",
    "Papakura South",
    "Opaheke",
    "Pukekohe North",
    "Rosehill",
    "Pahurehure",
    "Hingaia",
    "Runciman",
    "Kingseat",
    "Patumahoe",
    "Paerata-Cape Hill",
    "Hunua",
    "Mangatawhiri",
    "Paparata",
    "Bledisloe Park",
    "Pukekohe West",
    "Buckland",
    "Otaua",
    "Eden Road-Hill Top",
    "Bombay",
    "Awhitu",
    "Glenbrook",
    "Waiuku East",
    "South Waiuku",
    "Waiuku West",
    "Tuakau",
    "Kaiaua",
    "Pokeno",
    "Onewhero",
    "Te Akau",
    "Waikato Western Hills",
    "Ngaruawahia",
    "Te Pahu",
    "Te Uku",
    "Ormiston",
    "Chartwell",
    "Silverdale",
    "Hillcrest West",
    "Pukete",
    "Maeroa",
    "Nawton",
    "Grandview",
    "Crawshaw",
    "Te Rapa",
    "Swarbrick",
    "Dinsdale North",
    "Dinsdale South",
    "Bader",
    "Hamilton Lake",
    "Maramarua",
    "Meremere",
    "Waerenga",
    "Te Kauwhata",
    "Whitikahu",
    "Taupiri Community",
    "Gordonton",
    "Kainui",
    "Horsham Downs",
    "Opua West",
    "Homai West",
    "Newstead",
    "Eureka",
    "Matangi",
    "Tamahere-Tauwhare",
    "Karapiro",
    "Hautapu",
    "Swayne",
    "Cambridge West",
    "Cambridge Central",
    "Whangapouri Creek",
    "Bremner",
    "Te Awamutu East",
    "Te Awamutu Central",
    "Te Awamutu West",
    "Buckland South",
    "Te Awamutu South",
    "Rotokauri",
    "Opuawhanga",
    "Pukeoware",
    "Te Kowhai",
    "Whatawhata",
    "Brymer",
    "Temple View",
    "Inlet-Waiuku River",
    "Ngahinapouri",
    "Te Rore",
    "Lake Ngaroto",
    "Pirongia",
    "Pokuru",
    "Tokanui",
    "Rotowaro",
    "Lake Cameron",
    "Kaipaki",
    "Te Rahu",
    "Kihikihi Flat",
    "Pukerimu",
    "Rotoorangi",
    "Inlet-Aotea Harbour North",
    "Inlets-Otorohanga District",
    "Oceanic-Waikato Region West",
    "Kihikihi",
    "Inlet-Raglan Harbour",
    "Rotongata",
    "Otorohanga Rural West",
    "Whangaruru Harbour",
    "Te Kawa",
    "Otorohanga",
    "Otorohanga Rural East",
    "Inlet-Waitomo District",
    "Te Kuiti",
    "Marokopa",
    "Waipa Valley",
    "Mokauiti",
    "Tiroa",
    "Piopio",
    "Mahoenui",
    "Ngapuke",
    "Raurimu",
    "National Park",
    "Omori",
    "Kuratau",
    "Tokaanu",
    "Otangiwai-Heao",
    "Rangipo",
    "Tarrangower",
    "Taumarunui Central",
    "Sunshine-Hospital Hill",
    "Manunui",
    "Marotiri",
    "Sylvester",
    "Te Rerenga",
    "Coromandel",
    "Oceanic-Waikato Region East",
    "Whitianga",
    "Inlets-Thames-Coromandel District",
    "Islands-Thames-Coromandel District",
    "Ohinemuri",
    "Moanataiari",
    "Parawai",
    "Hikuai",
    "Te Puru-Thornton Bay",
    "Tairua",
    "Pauanui Beach",
    "Whangamata",
    "Turua",
    "Hauraki Plains",
    "Ngatea",
    "Kerepehi",
    "Te Rapa North",
    "Horotiu",
    "Paeroa",
    "Springdale",
    "Waihi",
    "Waihi Beach",
    "Morrinsville West",
    "Morrinsville East",
    "Arapuni",
    "Kawhia Community",
    "Tahuroa",
    "Matua",
    "Waihou-Walton",
    "Te Aroha",
    "Maraenui",
    "Waitoa",
    "Waharoa",
    "Okauia",
    "Te Poi",
    "Matamata North",
    "Tapapa",
    "Hinuera",
    "Matamata South",
    "Tirau",
    "Putaruru",
    "Lichfield",
    "Mangakaretu",
    "Ohura",
    "Matarawa",
    "Paraonui",
    "Stanley Park",
    "Parkdale",
    "Bays-Thames-Coromandel District",
    "Tokoroa Central",
    "Aotea",
    "Strathmore",
    "Amisfield",
    "Wawa",
    "Kinleith",
    "Otumoetai North",
    "Otumoetai South",
    "Bellevue",
    "Brookfield",
    "Te Reti",
    "Judea",
    "Sulphur Point",
    "Waikareao Estuary",
    "Tauranga Central",
    "Tauranga Hospital",
    "Tauranga South",
    "Gate Pa",
    "Yatton Park",
    "Inlet-Tauranga Harbour",
    "Greerton",
    "Maungatapu",
    "Kaitemako",
    "Welcome Bay West",
    "Welcome Bay East",
    "Inlet-Tauranga Harbour North",
    "Island View-Pios Beach",
    "Tahawai",
    "Aongatete",
    "Katikati Community",
    "Matakana Island",
    "Minden",
    "Omokoroa",
    "Te Puna",
    "Inlet-Tauranga Harbour Omokoroa",
    "Tauranga City-Marinas",
    "Bethlehem",
    "Bethlehem East",
    "Kaimai",
    "Pyes Pa",
    "Mt Maunganui North",
    "Hairini",
    "Motiti Island",
    "Mayor Island",
    "Omanu",
    "Arataki",
    "Te Maunga",
    "Oceanic-Bay of Plenty Region",
    "Palm Springs",
    "Pacific View",
    "Gravatt",
    "Palm Beach",
    "Ohauiti-Ngapeke",
    "Upper Papamoa",
    "Papamoa Beach East",
    "Doncaster",
    "Te Puke East",
    "Maketu Community",
    "Paengaroa",
    "Rangiuru",
    "Pongakawa",
    "Fenton",
    "Te Puke West",
    "Western Heights",
    "Selwyn Heights",
    "Fairy Springs",
    "Kawaha Point",
    "Koutu",
    "Mangakakahi",
    "Fordlands",
    "Pomare",
    "Sunnybrook",
    "Pukehangi North",
    "Pukehangi South",
    "Ohinemutu",
    "Kuirau",
    "Victoria",
    "Hillcrest",
    "Glenholme West",
    "Glenholme East",
    "Springfield",
    "Whaka",
    "Ngongotaha North",
    "Ngongotaha South",
    "Hamurana",
    "Tikitere",
    "Owhata West",
    "Poets Corner",
    "Owhata East",
    "Owhata South",
    "Ngapuna",
    "Tarawera",
    "Golden Springs",
    "Kaingaroa Forest",
    "Reporoa",
    "Ngakuru",
    "Waiwhero",
    "Arahiwi",
    "Mamaku",
    "Richmond Heights",
    "Poike",
    "Hilltop",
    "Athenree",
    "Tauhara",
    "Taupo Central",
    "Nukuhau",
    "Inland Water-Lake Taupo",
    "Tatua",
    "St Clair",
    "Oruanui",
    "Wairakei-Aratiatia",
    "Rangatira",
    "Lakewood",
    "Taupo East",
    "Maunganamu",
    "Wharewaka",
    "Waitahanui",
    "Taharua",
    "Motuoapa",
    "Turangi",
    "Tangiwai",
    "Moawhango",
    "Mangakino",
    "Maraetotara",
    "Ohope",
    "Waimana",
    "Inlet-Ohiwa Harbour West",
    "Poroporo",
    "Urewera",
    "Orini",
    "Otakiri",
    "Rotoma",
    "Taneatua",
    "Whakatane North",
    "Allandale-Mokorua",
    "Whakatane West",
    "Trident",
    "Moutohora Island",
    "Matapihi",
    "Kawerau",
    "Edgecumbe",
    "Matata",
    "Te Teko",
    "Murupara",
    "Matahina-Minginui",
    "Te Kaha",
    "Cape Runaway",
    "Oponae",
    "Waiotahi",
    "Opotiki",
    "East Cape",
    "Ruatoria",
    "Tokomaru Bay",
    "Tarndale-Rakauroa",
    "Te Karaka",
    "Wharekaka",
    "Tolaga Bay",
    "Wainui",
    "Matokitoki",
    "Makaraka",
    "Tiniroto",
    "Manutuke",
    "Te Hapara",
    "Gisborne Central",
    "Gisborne Airport",
    "Riverdale",
    "Mangapapa",
    "Whataupoko",
    "Kaiti North",
    "Outer Kaiti",
    "Tamarau",
    "Kaiti South",
    "Oceanic-Gisborne Region",
    "Raupunga",
    "Maungataniwha",
    "Tuai",
    "Inland Water-Lake Rotorua",
    "Ruakituri-Morere",
    "Whakaki",
    "Mahia",
    "Concord",
    "Poraiti",
    "Greenmeadows",
    "Meeanee",
    "Taradale South",
    "Awatoto",
    "Pakowhai",
    "Waiohiki",
    "Clive",
    "Whakatu",
    "Haumoana",
    "Waimarama",
    "Omahu",
    "Sherenden-Puketapu",
    "Puketitiri",
    "Bay View",
    "Tangoio",
    "Eskdale",
    "Rangatira Park",
    "Tutira",
    "Westshore",
    "Broadlands",
    "Tongariro",
    "Rangitaiki",
    "Hospital Hill",
    "Bluff Hill",
    "Onekawa West",
    "Oceanic-Hawke's Bay Region",
    "Nelson Park",
    "Mclean Park",
    "Marewa",
    "Te More",
    "Onekawa Central",
    "Onekawa South",
    "Pirimai",
    "Tamatea North",
    "Tamatea South",
    "Taradale North",
    "Maraekakaho",
    "Poukawa",
    "Pakipaki",
    "Coastlands",
    "Longlands South",
    "Havelock Hills",
    "White Island",
    "Te Mata",
    "Te Mata Hills",
    "Irongate",
    "Bridge Pa",
    "Raureka",
    "Kingsley-Chatham",
    "Twyford",
    "Karamu",
    "Lochain",
    "Flaxmere East",
    "Frimley",
    "Mahora",
    "St Leonards",
    "Hastings Central",
    "Inlet-Ohiwa Harbour East",
    "Mayfair",
    "Parkvale",
    "Akina",
    "Anderson Park",
    "Iona",
    "Havelock North Central",
    "Tikokino",
    "Patutahi",
    "Norsewood-Herbertville",
    "Elsthorpe-Flemington",
    "Waipawa",
    "Takapau",
    "Waipukurau",
    "Otane",
    "Porangahau",
    "Dannevirke East",
    "Inland Water-Lake Waikaremoana",
    "Dannevirke West",
    "Frasertown",
    "Nuhaka",
    "Woodville",
    "Papatawa",
    "Waitara West",
    "Waitara East",
    "Okoki-Okau",
    "Kaitake",
    "Okato",
    "Oakura",
    "Omata",
    "Barrett",
    "Carrington",
    "Fernleigh",
    "Struan Park",
    "Welbourn",
    "Highlands Park",
    "Glen Avon",
    "Lepperton",
    "Bell Block",
    "Bowden",
    "Mangaoraka",
    "Weston",
    "Frankleigh",
    "Westown",
    "Upper Westown",
    "Marfell",
    "Spotswood",
    "Lynmouth",
    "Moturoa",
    "Oceanic-Taranaki Region",
    "Kawaroa",
    "New Plymouth Central",
    "Marsland Hill",
    "Mount Bryan",
    "Fitzroy",
    "Brookvale",
    "Merrilands",
    "Inglewood",
    "Egmont Village",
    "Kaimata",
    "Stratford West",
    "Stratford East",
    "Woolwich",
    "Pembroke",
    "Midhirst",
    "Toko",
    "Camberley",
    "Douglas",
    "Whangamomona",
    "Kahui",
    "Rahotu",
    "Opunake",
    "Eltham",
    "Mangatoki-Moeroa",
    "Hawera North",
    "Hawera South",
    "Otaki",
    "Ohangai",
    "Tawhiti",
    "Hawera West",
    "Waingongoro",
    "Okaiawa",
    "Manaia",
    "Kapuni",
    "Patea",
    "Waverley",
    "Whenuakura",
    "Raetihi",
    "Makakaho",
    "Ohakune",
    "Putiki",
    "Blueskin",
    "Mosston",
    "Maxwell",
    "Tawhero",
    "Otamatea",
    "Fordell-Kakatahi",
    "Marybank-Gordon Park",
    "Wembley Park",
    "Williams Domain",
    "Paraite",
    "Kowhai Park",
    "Bastia Hill",
    "Durie Hill",
    "Cooks Gardens",
    "Wanganui Central",
    "Laird Park",
    "St Johns Hill",
    "Lower Aramoho",
    "Upper Aramoho",
    "Castlecliff North",
    "Castlecliff South",
    "Balgownie",
    "Gonville West",
    "Springvale West",
    "Springvale East",
    "Wanganui Collegiate",
    "Port-Taranaki",
    "Gonville East",
    "Gonville South",
    "Spriggens Park",
    "Oceanic-Manawatu-Wanganui Region",
    "Pohonui-Porewa",
    "Hunterville",
    "Lake Alice",
    "Marton",
    "Levin North",
    "Bulls",
    "Feilding West",
    "Taihape",
    "Waiouru",
    "Ashhurst",
    "Tokorangi-Hiwinui",
    "Feilding East",
    "Stoney Creek",
    "Feilding Central",
    "Halcombe",
    "Feilding North",
    "Pohangina",
    "Kiwitea",
    "Linden",
    "Foxton",
    "Foxton Beach",
    "Kaponga",
    "Himatangi Beach",
    "Oroua Downs-Waitohi",
    "Moutoa",
    "Rongotea",
    "Rakiraki",
    "Sanson",
    "Ohakea",
    "Tangimoana",
    "Milson",
    "Awapuni West",
    "Kairanga",
    "Kauwhata",
    "Turitea",
    "Linton Military Camp",
    "Aokautere",
    "Massey University",
    "Awapuni North",
    "Normanby",
    "Awapuni South",
    "West End",
    "Waitotara",
    "Hokowhitu West",
    "Hokowhitu Lagoon",
    "Cloverlea",
    "Westbrook",
    "Highbury",
    "Takaro",
    "Palmerston North Central",
    "Palmerston North Hospital",
    "Papaeoia",
    "Waitarere",
    "Kelvin Grove",
    "Roslyn",
    "Terrace End",
    "Mill Road",
    "Hokowhitu East",
    "Opiki",
    "Tokomaru",
    "Mangaore-Manakau",
    "Lake Horowhenua",
    "Kohitere",
    "Waiopehu",
    "Shannon",
    "Levin East",
    "Playford Park",
    "Levin West",
    "Levin South",
    "Waikanae Beach",
    "Waikanae West",
    "Waikanae East",
    "Waikanae Park",
    "Otaki Forks",
    "Kaitawa",
    "Te Horo",
    "Elderslea",
    "Poets Block",
    "Brentwood",
    "Wallaceville",
    "Trentham North",
    "Heretaunga-Silverstream",
    "Trentham South",
    "Pinehaven",
    "Mangaroa",
    "Heretaunga",
    "Riverstone Terraces",
    "Moonshine Valley",
    "Upper Hutt Central",
    "Ebdentown",
    "Clouston Park",
    "Totara Park",
    "Emerald Hill",
    "Akatarawa",
    "Maoribank",
    "Te Marua",
    "Cloustonville",
    "Haywards-Manor Park",
    "Kelson",
    "Belmont",
    "Tirohanga",
    "Normandale",
    "Maungaraki",
    "Alicetown",
    "Melling",
    "Delaney",
    "Manuka",
    "Tawhai",
    "Holborn",
    "Taita North",
    "Taita South",
    "Boulcott",
    "Avalon West",
    "Epuni West",
    "Avalon East",
    "Ratana Community",
    "Epuni East",
    "Naenae South",
    "Naenae North",
    "Moera",
    "Woburn North",
    "Woburn South",
    "Hutt Central",
    "Ngamatea",
    "Waterloo West",
    "Waterloo East",
    "Waiwhetu North",
    "Waiwhetu South",
    "Gracefield",
    "Mangaweka",
    "Maewa",
    "Eastbourne",
    "Tawa South",
    "Tawa Central",
    "Greenacres",
    "Paraparaumu Central",
    "Maungakotukutuku",
    "Paraparaumu Beach North",
    "Kapiti Island",
    "Paraparaumu Beach South",
    "Raumati Beach",
    "Raumati South",
    "Paekakariki",
    "Arakura",
    "Glendale",
    "Parkway",
    "Fernlea",
    "Homedale West",
    "Homedale East",
    "Pencarrow",
    "Esplanade",
    "Wilford",
    "Petone Central",
    "Korokoro",
    "Inlet-Wellington Harbour",
    "Elsdon-Takapuwahia",
    "Titahi Bay South",
    "Titahi Bay North",
    "Onepoto",
    "Cannons Creek North",
    "Cannons Creek South",
    "Whakarongo",
    "Longburn",
    "Ranui Heights",
    "Porirua Central",
    "Paekakariki Hill",
    "Plimmerton",
    "Takapu",
    "Porirua East",
    "Papakowhai North",
    "Papakowhai South",
    "Ascot Park",
    "Waitangirua",
    "Cannons Creek East",
    "Pukerua Bay",
    "Mana-Camborne",
    "Paremata-Postgate",
    "Discovery",
    "Endeavour",
    "Adventure",
    "Oceanic-Wellington Region",
    "Inlet-Porirua Harbour",
    "Paparangi",
    "Newlands North",
    "Newlands South",
    "Johnsonville East",
    "Paparangi West",
    "Johnsonville North",
    "Johnsonville Central",
    "Ngauranga West",
    "Raroa",
    "Grenada North",
    "Woodridge",
    "Churton Park North",
    "Churton Park South",
    "Makara-Ohariu",
    "Khandallah Park-Broadmeadows",
    "Rangoon Heights",
    "Te Kainga",
    "Kaiwharawhara",
    "Awarua",
    "Ngaio South",
    "Wadestown",
    "Thorndon-Tinakori Road",
    "Wilton",
    "Northland North",
    "Crofton Downs",
    "Karori North",
    "Karori Park",
    "Burbush",
    "Karori East",
    "Karori South",
    "Lambton",
    "Te Motu Island",
    "Willis Street-Cambridge Terrace",
    "Wellington City-Marinas",
    "Oriental Bay",
    "Mt Victoria West",
    "Mt Cook-Wallace Street",
    "Adelaide",
    "Northland",
    "Kelburn",
    "Mitchelltown",
    "Aro Street-Nairn Street",
    "Taharoa",
    "Brooklyn",
    "Owhango",
    "Newtown West",
    "Berhampore East",
    "Newtown East",
    "Melrose-Houghton Bay-Southgate",
    "Berhampore West",
    "Lyall Bay-Airport-Moa Point",
    "Kilbirnie East",
    "Kilbirnie West-Hataitai South",
    "Roseneath",
    "Hataitai North",
    "Otaihanga",
    "Brooklyn South",
    "Happy Valley-Owhiro Bay",
    "Island Bay West",
    "Island Bay East",
    "Kingston-Mornington",
    "Vogeltown West",
    "Vogeltown",
    "Maupuia",
    "Miramar West",
    "Miramar North",
    "Miramar",
    "Miramar South",
    "Karaka Bay-Worser Bay",
    "Seatoun",
    "Strathmore Park",
    "Pahiatua",
    "Mangatainoka",
    "Owahanga",
    "Nireaha-Tiraumea",
    "Eketahuna",
    "Kopuaranga",
    "Solway North",
    "Solway South",
    "Masterton West",
    "Masterton East",
    "Masterton Central",
    "Ngaumutawa",
    "Masterton Railway",
    "Lansdowne",
    "Opaki-Fernridge",
    "Atmore",
    "Homebush-Te Ore Ore",
    "Whareama",
    "Carterton",
    "Mt Holdsworth",
    "Te Wharau",
    "Waingawa",
    "Greytown",
    "Featherston",
    "Kahutara",
    "Tuturumuri",
    "Martinborough",
    "Mana Island",
    "Spring Creek-Grovetown",
    "Rapaura",
    "Tuamarina",
    "Marlborough Sounds Terrestrial",
    "Waikawa",
    "Picton",
    "Pauatahanui",
    "Marlborough Sounds Coastal Marine",
    "Havelock",
    "Resolution",
    "Wairau South",
    "Fairhall",
    "Renwick",
    "Ngauranga East",
    "Woodbourne",
    "Omaka",
    "Springlands",
    "Mayfield",
    "Riverlands",
    "Witherlea",
    "Weld Pass",
    "Whitney",
    "Blenheim Central",
    "Glenside North",
    "Grenada Village",
    "Redwoodtown",
    "Ward",
    "Severn",
    "Seddon",
    "Bronte",
    "Parnassus",
    "Amuri",
    "Kaikoura Rural",
    "Kaikoura Township",
    "Atawhai",
    "The Wood",
    "Trafalgar",
    "Grampians",
    "Britannia",
    "Washington",
    "Toi Toi",
    "Broads",
    "Kirks",
    "The Brook",
    "Oceanic-Marlborough Region",
    "Tahunanui",
    "Tahuna Hills",
    "Nelson Airport",
    "Langbein",
    "Enner Glynn",
    "Maitlands",
    "Nayland",
    "Motuopae Island",
    "Isel Park",
    "Takaka",
    "Oceanic-Tararua Constituency",
    "Golden Bay",
    "Oceanic-Tasman Region",
    "Motueka Outer",
    "Mapua",
    "Wai-Iti",
    "Taitville",
    "Wakefield",
    "Brightwater",
    "Ranzau",
    "Waimea Inlet West",
    "Saxton Island",
    "Ngawhatu",
    "Richmond Hill",
    "Richmond East",
    "Richmond West",
    "Kaiteriteri",
    "Riwaka",
    "Motueka East",
    "Motueka West",
    "Golden Downs",
    "Tapawera",
    "Lake Rotoroa",
    "Murchison",
    "Granity",
    "Little Wanganui",
    "Karamea",
    "Hector-Ngakawau",
    "Buller Coalfields",
    "Westport Rural",
    "Charleston",
    "Westport Urban",
    "Reefton",
    "Inangahua Valley",
    "Mawheraiti",
    "Ahaura",
    "Haupiri",
    "Nelson Creek-Ngahere",
    "Arnold Valley",
    "Barrytown",
    "Blackball",
    "Kaiata",
    "Dobson",
    "Cobden",
    "Greymouth Central",
    "Greymouth South",
    "Blaketown",
    "Karoro",
    "Greymouth Rural",
    "Mara",
    "South Beach-Camerons",
    "Marsden-Hohonu",
    "Oceanic-West Coast Region",
    "Haast",
    "Bruce Bay-Paringa",
    "Karangarua",
    "Fox Glacier",
    "Hokitika Urban",
    "Whataroa",
    "Waiho",
    "Franz Josef",
    "Waitaha",
    "Harihari",
    "Ross",
    "Totara River",
    "Hokitika Valley",
    "Kumara",
    "Taramakau",
    "Hanmer Springs",
    "Culverden",
    "Cheviot",
    "Hurunui",
    "Okuku",
    "Leithfield",
    "Loburn",
    "Sefton",
    "Ashley",
    "Inland Water-Lake Wairarapa",
    "Amberley",
    "Rangiora North",
    "Rangiora West",
    "Rangiora East",
    "Waikuku",
    "Coldstream",
    "Woodend",
    "Kingsbury",
    "Southbrook",
    "Tuahiwi",
    "Lehmans",
    "Cust",
    "Kaiapoi North West",
    "Kaiapoi East",
    "Kaiapoi South",
    "Courtenay",
    "Whangamoa",
    "Kaiapoi West",
    "Mansfield",
    "Ohoka",
    "Mandeville",
    "Clarkville",
    "Ashley Gorge",
    "Oxford",
    "Wairau North",
    "Malvern",
    "Kirwee",
    "Darfield",
    "Burnham Military Camp",
    "Mona Vale",
    "Riccarton West",
    "Riccarton",
    "Riccarton South",
    "Sockburn",
    "Clifton",
    "Inlet-Tasman Bay",
    "Wigram",
    "Oceanic-Nelson Region",
    "Oceanic-Canterbury Region North",
    "Oaklands East",
    "Halswell South",
    "Aidanfield",
    "Halswell Domain",
    "Oaklands West",
    "Westmorland",
    "Kennedys Bush",
    "Taitapu",
    "Hornby North",
    "Islington",
    "Broomfield",
    "Hornby South",
    "West Melton",
    "Yaldhurst",
    "Paparua",
    "Best Island",
    "Rabbit Island",
    "Templeton",
    "Aniseed Hill",
    "Hope",
    "Saxton",
    "Trents-Ladbrooks",
    "Prebbleton",
    "Styx",
    "Glenduan",
    "Highfield Park",
    "Travis Wetland",
    "Waimairi Beach",
    "Parklands",
    "Westhaven",
    "Mairehau North",
    "Redwood South",
    "Redwood North",
    "Casebrook",
    "Styx Mill",
    "Belfast",
    "Moutere Inlet",
    "Inlet-Motueka",
    "Mokihinui",
    "Inangahua Junction",
    "Orowaiti",
    "Inlet-Buller River",
    "Jellie Park",
    "Lake Brunner",
    "Wairarapa",
    "Burnside",
    "Russley",
    "Runanga-Rapahoe",
    "Point Elizabeth",
    "Bishopdale",
    "Harewood",
    "Bishopdale North",
    "Sawyers Arms",
    "Belfast South",
    "Hawthornden",
    "Merrin",
    "Avonhead West",
    "Avonhead",
    "Westburn",
    "Ilam",
    "Hokitika Rural",
    "Middleton",
    "Kaniere",
    "Wharenui",
    "Upper Riccarton",
    "Fendalton",
    "Waimea-Arahura",
    "Otira",
    "Deans Bush",
    "Holmwood",
    "Bryndwr",
    "Cashmere West",
    "Cashmere East",
    "Waiau",
    "St Martins",
    "Rapaki Track",
    "Mt Pleasant",
    "Heathcote Valley",
    "South Brighton",
    "New Brighton",
    "Rawhiti",
    "North Beach",
    "Linwood East",
    "Wainoni",
    "Bexley",
    "Rangiora Central",
    "Aranui",
    "Pegasus",
    "Kaiapoi North East",
    "Pines-Kairaki Beach",
    "Woodend Beach",
    "Avondale",
    "Bromley",
    "Ensors",
    "Travis",
    "Fernside",
    "West Eyreton",
    "Opawa",
    "Woolston South",
    "Ferrymead",
    "Silverstream",
    "Woolston West",
    "Shirley West",
    "Shirley East",
    "Eyrewell",
    "Dallington",
    "Burwood",
    "Phillipstown",
    "Linwood",
    "Linwood North",
    "Avonside",
    "Sydenham",
    "Hendersons Basin",
    "Waltham",
    "Beckenham",
    "Hillmorton",
    "Hoon Hay",
    "Hoon Hay South",
    "Barrington South",
    "Prestons",
    "Barrington North",
    "Spreydon",
    "Somerfield",
    "Cathedral Square",
    "Papanui",
    "Avon Loop",
    "Lincoln",
    "Addington",
    "Northcote",
    "Aorangi",
    "Strowan",
    "Merivale",
    "Hagley Park",
    "Mairehau",
    "Rutland",
    "St Albans West",
    "St Albans East",
    "Richmond South",
    "Edgeware",
    "Richmond North",
    "Avon-Heathcote Estuary",
    "Moncks Bay",
    "Sumner",
    "Lyttelton",
    "Governors Bay",
    "Diamond Harbour",
    "Port Levy",
    "Inlet-Port Lyttelton",
    "Oceanic-Canterbury Region South",
    "Little River",
    "Banks Peninsula Eastern Bays",
    "Akaroa",
    "Chatham Islands",
    "Springston",
    "Rolleston Central",
    "Rolleston North East",
    "Rolleston North West",
    "Rolleston South West",
    "Selwyn-Rakaia",
    "Inland Water-Lake Ellesmere North",
    "Leeston",
    "Southbridge",
    "Ashburton Central West",
    "Ashburton Central East",
    "Hampstead",
    "Netherby",
    "Allenton East",
    "Allenton West",
    "Tinwald",
    "Hinds",
    "Plains Railway",
    "Ashburton East",
    "Chertsey",
    "Fairton",
    "Ashburton North",
    "Mt Somers",
    "Methven",
    "Geraldine",
    "Ben Mcleod",
    "Orari",
    "Temuka",
    "Winchester",
    "Levels",
    "Washdyke",
    "Gleniti",
    "Glenwood",
    "Otipua Creek-Washdyke Flat",
    "Maori Park",
    "Waimataitai",
    "Marchwiel",
    "Highfield",
    "Fraser Park",
    "Seaview",
    "Watlington",
    "Parkside",
    "Timaru Gardens",
    "Redruth",
    "Mackenzie",
    "Fairlie",
    "Twizel Community",
    "Oamaru South",
    "Lake Tekapo",
    "Waihao",
    "Waimate",
    "Inlet-Port Napier",
    "Maheno",
    "Pukeuri",
    "Ardgowan",
    "Cape Wanbrow",
    "Hampden",
    "Oamaru Central",
    "Orana Park",
    "Oamaru North",
    "Otago University",
    "Quail Island",
    "Oceanic-Otago Region",
    "Inlets-Banks Peninsula Bays",
    "Aviemore",
    "Otematata",
    "Kurow",
    "Omarama",
    "Palmerston",
    "Waihemo",
    "Hyde",
    "Waikouaiti",
    "Inland Water-Lake Ellesmere South",
    "Nenthorn",
    "Evansdale",
    "Oceanic-Chatham Islands",
    "Waitati",
    "Port Chalmers",
    "Inlet-Otago Harbour",
    "Sawyers Bay",
    "St Leonards-Blanket Bay",
    "Rolleston South East",
    "North Dunedin",
    "Whanawhana",
    "North East Valley",
    "Pine Hill",
    "Bare Island",
    "Forrester Park",
    "Ravensbourne",
    "Brockville",
    "Roslyn North",
    "Halfway Bush",
    "Woodhaugh",
    "Maori Hill",
    "Rakaia",
    "Harbourside",
    "Fernhill",
    "High St-Stuart St",
    "Stuart St-Frederick St",
    "Roslyn South",
    "Inlet-Dunedin City Bays",
    "Corstorphine East",
    "Pareora",
    "Belleknowes",
    "South Dunedin",
    "Pleasant Point",
    "Caledonian",
    "Musselburgh",
    "Andersons Bay",
    "Macandrew Bay",
    "Broad Bay-Portobello",
    "Company Bay",
    "Sandymount",
    "St Kilda West",
    "St Kilda Central",
    "St Kilda East",
    "Abbotsford",
    "Green Island",
    "Inlet-Port Timaru",
    "Strath Taieri",
    "Bush Road",
    "Mosgiel East",
    "Inland Water-Lake Tekapo",
    "Mosgiel South",
    "East Taieri",
    "Waldronville",
    "Fairfield",
    "St Andrews",
    "Brighton",
    "Outram",
    "Taieri",
    "Saddle Hill",
    "Wingatui",
    "Wyllies Crossing",
    "Kaikorai Hill",
    "Duntroon",
    "Bruce",
    "Benhar",
    "Kaitangata",
    "Urenui",
    "Milton",
    "Balclutha",
    "Clutha",
    "Owaka",
    "Toetoes",
    "Clinton",
    "Chatton",
    "Kaiwera",
    "Tuapeka",
    "Teviot",
    "Roxburgh",
    "Lawrence",
    "Tapanui",
    "Maniototo",
    "Warrington",
    "Ranfurly",
    "Naseby",
    "Dunstan",
    "Waikaia",
    "Clyde",
    "Alexandra",
    "Hawea",
    "Cromwell",
    "Glenleith",
    "Oceanic-Oil Rigs Taranaki",
    "Queenstown Bay",
    "Queenstown Hill",
    "Arrowtown",
    "Wanaka",
    "Oceanic-Southland Region",
    "Frankton",
    "Arthurs Point",
    "Corstorphine West",
    "Inland Water-Lake Wakatipu",
    "Matukituki",
    "Outer Wakatipu",
    "Sunshine Bay",
    "Lake Hayes South",
    "Wakatipu Basin",
    "Kelvin Heights",
    "Kingston South",
    "Lumsden Community",
    "Hokonui",
    "Inner Peninsula",
    "Kaweku",
    "Riversdale Community",
    "Charlton",
    "Taiaroa-Cape Saunders",
    "West Gore",
    "South Gore",
    "Central Gore",
    "North Gore",
    "East Gore",
    "Mataura",
    "Ohawe Beach",
    "Stirling",
    "Winton",
    "Waianiwa",
    "Wallacetown",
    "Makarewa North",
    "Makarewa",
    "Oreti Beach",
    "Otatara",
    "Bushy Point",
    "Dacre",
    "Woodlands",
    "Inland Water-Lake Hawea",
    "Waikiwi",
    "Mill Road-Woodend",
    "Myross Bush",
    "Wyndham",
    "Grasmere",
    "Inland Water-Lake Wanaka",
    "West Invercargill",
    "Otakaro Park",
    "Lake Hayes",
    "Crinan",
    "Appleby-Kew",
    "Gladstone-Avenal",
    "Rosedale",
    "Windsor",
    "Waverley-Glengarry",
    "Hawthorndale",
    "Richmond",
    "Newfield-Rockdale",
    "Georgetown",
    "Heidelberg",
    "Fairfax",
    "Strathern",
    "Kingswell-Clifton",
    "Bay Road West",
    "Tisbury",
    "Stewart Island",
    "Bluff",
    "Greenhills",
    "Inlet-Bluff Harbour",
    "Waituna",
    "Edendale Community",
    "Campbell Island",
    "Te Anau",
    "Fiordland",
    "Mararoa River",
    "Mossburn",
    "Dog Island",
    "Glenorchy",
    "Milford",
    "Otautau",
    "Ohai",
    "Wairio",
    "Nightcaps",
    "Inlet-New River Estuary",
    "Oceanic-Oil Rig Southland",
    "Oceanic-Auckland Islands",
    "Auckland Islands",
    "Inland Water-Lake Manapouri",
    "Inland Water-Lake Te Anau",
    "Te Waewae",
    "Riverton East",
    "Oceanic-Snares Islands",
    "Riverton West",
    "Tuatapere",
    "NZ Economic Zone",
    "Antipodes Islands",
    "Frankton East",
    "Koitiata",
    "Jacks Point",
    "Horokiwi",
    "Manapouri",
    "Fairview-Scarborough",
    "Newlands East",
    "Kaka Point",
    "Seatoun Tunnel West",
    "Kakanui",
    "Akaroa Harbour",
    "Port Nelson",
    "Waimea Inlet East",
    "Inlet-Ligar Bay",
    "Jackett Island",
    "Dunsandel",
    "Maruia",
    "Atarau",
    "Kairua",
    "Lake Tennyson",
    "Halswell West",
    "Helensburgh",
    "Camside",
    "Woodend West",
    "Mcleans Island",
    "Peka Peka",
    "Aramoana",
    "Karitane",
    "Maitai",
    "Mairaki",
    "Mt Cook",
    "Oroua Bridge",
    "Allen Road",
    "Redoubt",
    "Inland Water-Lake Alexandrina",
    "Maidstone",
    "Middlemarch",
    "Inlet-Kaipara River",
    "Muriwai Valley",
    "Tiwai Point",
    "Inlet-Milford Sound",
    "Inland Water-Lake Hauroko",
    "Inlet-Jacobs River Estuary",
    "Bounty Islands",
    "Oceanic-Antipodes Islands",
    "Mokohinau Island",
    "Tidal-Great Barrier Island",
    "Seaview Marina",
    "Evans Bay Marina",
    "Bell Island",
    "Coal Creek",
    "Ravenswood",
    "Inlet-Port Oamaru",
    "Inland Water-Lake Ohau",
    "Balfour Community",
    "Oceanic-Campbell Island",
    "Centre Island",
    "Ross Dependency",
    "Oceanic-Bounty Islands",
    "Snares Island",
    "Three Kings Islands"
];

module.exports = {
    NZPlaces
}