const Secrets = [
    "doesn't have a secret",
    "enjoys the taste of rain",
    "bathes in blood",
    "looks out for others",
    "has a taste for human flesh",
    "eats bees",
    "takes ice-cream baths",
    "looks at cat pictures on the internet",
    "has a six-foot long tongue",
    "sniffs paint",
    "eats toenail clippings",
    "enthuses over jelly wrestling",
    "slacks off during Zoom meetings",
    "has multiple Reddit accounts",
    "is into crypto",
    "is a simp for cats",
    "can breathe in space",
    "eats other birds",
    "stays too long",
    "won't leave",
    "collects shells",
    "collects stamps",
    "collects coins",
    "collects tiny skulls",
    "runs a tiny bird cult",
    "longs for the void",
    "burns ants",
    "drinks milk from the source",
    "tans in the light of the Moon",
    "is immortal",
    "seeks immortality",
    "collects leaves",
    "collects rare crypto",
    "is Satoshi Nakamoto",
    "longs to drive F1 cars",
    "recommends obscure music",
    "cannot fly",
    "can fly at more than 400 mph",
    "has achieved enlightenment",
];

module.exports = {
    Secrets
}