const Secrets = [
    "doesn't have a secret",
    "enjoys the taste of rain",
    "bathes in blood",
    "looks out for others",
    "has a taste for human flesh",
    "eats bees",
    "takes ice-cream baths",
    "looks at cat pictures on the internet",
    "has a six-foot long tongue",
    "sniffs paint",
    "eats toenail clippings",
    "enthuses over jelly wrestling",
    "slacks off during video meetings",
    "has multiple sockpuppet accounts",
    "is into crypto",
    "is a simp for cats",
    "can breathe in space",
    "eats other birds",
    "stays too long",
    "won't leave",
    "collects shells",
    "collects stamps",
    "collects coins",
    "collects tiny skulls",
    "runs a tiny bird cult",
    "longs for the void",
    "burns ants",
    "drinks milk from the source",
    "tans in the light of the Moon",
    "is immortal",
    "seeks immortality",
    "collects leaves",
    "collects rare crypto",
    "is Satoshi Nakamoto",
    "longs to drive F1 cars",
    "recommends obscure music",
    "cannot fly",
    "can fly at more than 400 mph",
    "has achieved enlightenment",
    "doesn't bathe",
    "listens",
    "cares",
    "lives, loves, laughs.",
    "yeets",
    "beats",
    "helps NEETs",
    "is a giant chad",
    "is an enormous chad",
    "is the chad of all chads",
    "the chaddiest chad that ever chadded",
    "is a chaddy boi",
    "is delicate",
    "is entirely satisfied",
    "is content",
    "has a good job",
    "doesn't care",
    "cares too much",
    "cares for plants",
    "is the Dark Lord of all it surveys",
    "can travel faster than light",
    "is not subject to the laws of physics",
    "is too good",
    "isn't good enough",
    "suffers from insecurity",
    "will fight you",
    "eats too much",
    "eats too little",
    "has an appetite for destruction",
    "has an appetite for creation",
    "spreads woe",
    "sparks joy",
    "sparks fear",
    "sets small fires",
    "wants to put a dent in the world",
    "dislikes his job",
    "is just going through the motions",
    "is rambunctious",
    "has a deep and profound spirituality",
    "looks deep within the souls of others and sees the agony within",
    "knows you better than you know yourself",
    "is the living avatar of Justice",
    "is the living avatar of Truth",
    "is the living avatar of Avatars",
    "is the living avatar of Disappointment",
    "is the living avatar of Nope",
    "is the living avatar of Bonk",
    "goes bonk",
    "nopes out",
    "disappoints",
    "creeps about at night",
    "eavesdrops",
    "drops sick beats",
    "is stronk",
    "is a meme",
    "is actually Canadian",
    "has powers that could shatter the foundations of the earth",
    "is stronger than the foundations of the earth",
    "will diminish, and go into the West",
    "says \"eyyyyy\"",
    "is inappropriate",
    "is problematic",
    "has problematic faves",
    "enthuses over niche topics",
    "is one of those people that goes \"ba ba ba, cha cha ka-chow\"",
    "taps along to the beat of the music",
    "sneezes unnecessarily loudly",
    "doesn't sneeze properly",
    "will give you up and let you down",
    "will never give you up and never let you down",
    "is never gonna run around and desert you",
    "is never gonna make you cry",
    "is never gonna say goodbye",
    "is never gonna tell a lie and hurt you",
    "will run around and desert you",
    "will make you cry",
    "will say goodbye, tell a lie, and hurt you",
    "disdains birdseed",
    "spells it wrong",
    "can't tell the difference between its and it's",
    "mixes up their, there, and they're ",
    "doesn't use Oxford commas",
    "talks too wise",
    "risks it all on one turn of pitch-and-toss",
    "has another, smaller bird inside it",
    "lays bad eggs",
    "is mean",
    "is nice",
    "is stanky",
    "is loopy",
    "is a lil' ball of love and affection",
    "does salacious dances on video for clout",
    "has no clout",
    "spreads disinformation",
    "spreads conspiracies",
    "spreads rumours",
    "spreads butter",
    "lays golden eggs",
    "writes bestselling books about wizards before going into a very public decline",
    "takes memes seriously",
    "thinks memes are serious business",
    "enjoys contemporary art",
    "owes money",
    "doesn't think things through",
    "has the texture of jelly",
    "has the texture of onions",
    "has the texture of old carpet",
    "has the texture of brushed metal",
    "has the texture of a wet dog nose",
    "lives in a giant bucket",
    "didn't bring a coat",
    "doesn't contribute to the pot-luck",
    "eats, shoots, and leaves",
    "eats shoots and leaves",
    "went to the levy but the levy was dry",
    "is much too heavy",
    "asks others \"Do I look fat in this?\"",
    "is a total Karen",
    "is a total Karen to shop assistants",
    "doesn't tip",
    "tips generously",
    "treats retail workers well",
    "buys NFTs",
    "talks too much about NFTs",
    "spends far too much time and energy on a simple joke",
    "doesn't show up to D&D sessions",
    "never shows",
    "is always late",
    "is always early",
    "is always on time",
    "is never late, nor early, arrives precisely when means to",
    "is a motherflippin' wizard",
    "spells \"gutted\" as \"guttered\", and doesn't realise it's wrong",
    "is one of those people who use ellipses instead of full stops in Facebook arguments",
    "is a Boomer",
    "owns property",
    "owns several rental properties which are poorly maintained",
    "votes Right",
    "votes Left",
    "is an enlightened centrist",
    "doesn't recycle",
    "recycles assiduously",
    "engages in parasocial relationships",
    "stans inappropriately",
    "stans too hard",
    "can roll into a ball",
    "came in like a wrecking ball",
    "tells its secrets to everyone so they're no longer secret, are they",
    "cannot keep secrets",
    "kills houseplants through neglect",
    "gets really enthused about something for six weeks but then abandons it never to speak of it again",
    "enthuses over sunsets",
    "gets distracted easily",
    "cries over anime",
    "is suss",
    "did an outdoor education course three years ago and won't shut up about how impactful it was",
    "keeps time",
    "grooves to the beat",
    "doesn't stop, never gives up, holds its head high and reaches the top",
    "whistles a few bars of an earworm and then you have to live with it for the rest of the day",
    "can't sing",
    "can sing",
    "sings really well actually",
    "can sing, but only songs you hate",
    "plays the guitar but only the same three songs that it learned as a teenager",
    "plays guitar, poorly",
    "plucks at its feathers",
    "can code in assembly language",
    "Invented the 'Bofa deez Nuts' joke",
    "needs to take a chill pill",
    "has too many kinks",
    "has boring kinks",
    "speaks out of turn",
    "seems to be listening but is actually asleep",
    "talks about JRPGs",
    "talks about anime",
    "talks about D&D",
    "has the second personality of a ruthless bully",
    "cant stop singing the chorus of \"Stop Drop & Roll - Mareko feat. Deceptikonz\" but as \"Eat Sausage Rolls\"",
    "perfectly mimics your phone ringtone",
    "sighs too loudly",
    "audibly sighs when a bad email comes in",
    "Is sadly a Australian",
    "Is sadly a Canadian",
    "howls at the moon",
    "howls at the sun",
    "is a lumberjack",
    "is a lumberjack and is OK",
    "likes to push the pram a lot",
    "works all night and sleeps all day",
    "sleeps all night and works all day",
    "hangs around in bars",
    "hangs upside down to sleep",
    "lives in a beehive",
    "wishes it was a mole",
    "longs to burrow underground",
    "longs for the ocean",
    "longs for the skies",
    "wishes the property market would crash",
    "trusts the Free Market to sort everything out",
    "believes in the Invisible Hand of the Free Market",
    "calls cats \"Fur Chickens\"",
    "just can't",
    "can moo",
    "secretly aspires to become a surgeon",
    "secretly aspires to become a politician",
    "secretly aspires to secretly aspire",
    "has recursive secrets",
    "has redundant secrets and redundant secrets",
    "hits the \"I'm Feeling Lucky\" button",
    "after a fungal infection acquired the nickname \"Fun Gus\"",
    "has interesting kinks",
    "talks about kinks",
    "aspires to have kinks",
    "wasted three wishes on frivolous things",
    "wishes it was a cat",
    "wishes it was a dog",
    "wishes it was a better bird",
    "procrastinates",
    "abandoned hobbies",
    "does tiny watercolours",
    "was arrested for pooping on a US President",
    "thinks they're a influencer (they're not)",
    "is otherwise known as the tinder swindler",
    "invented birdporn",
    "flies kites at night",
    "strains the ocean for krill with a mouth full of baleen",
    "searches without stopping",
    "is searching for a heart of gold",
    "knows the meaning of life",
    "knows more than you",
    "is intelligent to the point of never knowing happiness",
    "has never known happiness",
    "longs for happiness",
    "messes around in boats",
    "has been there and back again",
    "wishes it was somewhere else",
    "just does it",
    "bores easily",
    "can't concentrate",
    "can only concentrate on things it finds funny",
    "yawns bigly",
    "is assembling a small low-yield nuclear device",
    "won't stop talking about electric cars",
    "simps for billionaires",
    "is a very good bird",
    "is the best bird",
    "owns a vest made from dachshunds",
    "thinks the show only got better after Season 9",
    "has unpopular opinions",
    "has incorrect opinions",
    "only has correct opinions",
    "speaks truth",
    "is the Kwisatz Haderach",
    "can spell Kwisatz Haderach without needing to look it up",
    "will set humanity on the Golden Path",
    "is prescient",
    "can instantly point out the problematic part of any given movie or show",
    "enjoys spreadsheets",
    "buys limited-edition box sets",
    "has an untouched video game backlog stretching back to 2005",
    "uses hacks",
    "uses aimbots",
    "thinks the series peaked with Season 7",
    "isn't interested",
    "can't be convinced",
    "believes false facts",
    "believes in false gods",
    "serves a false god",
    "will outlast us all",
    "is part of the immutable, eternal blockchain, forever and ever, amen",
    "spends too much time scrolling",
    "spends time on pointless things",
    "regrets spending on NFTs",
    "collects NFTs",
    "thinks monkey JPGs are worth actual money",
    "thinks this whole thing might just work somehow",
    "serves the One True God",
    "has bathed in the blood of the Lamb",
    "is the Harbinger",
    "virtue signals",
    "signals virtue",
    "is a bird"
];

module.exports = {
    Secrets
}